esphome:
  name: "polycab-hohm-batten-1"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Polycab-Hohm-Batten-1"
    password: "a1b2c3d4e5f6"

captive_portal:
  
output:
  - platform: esp8266_pwm
    id: brightness_pwm
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp_pwm
    pin: GPIO13
    inverted: true

light:
  - platform: color_temperature
    name: "polycab-hohm-batten-1"
    color_temperature: color_temp_pwm
    brightness: brightness_pwm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
